### ISSUE TITLE
Investigate write_once buckets in Ruby [JIRA: CLIENTS-307]

### ISSUE THREAD

**Issue by Basho-JIRA** [basho/riak-ruby-client#214]
null

**[Created in JIRA by Bryce Kerley]**

**Comment by bkerley** [comment]
# engage stream of consciousness

1. Modify https://github.com/basho-labs/riak-ruby-vagrant/tree/bk-210pre3 to use 2.1.0pre3 (URL for precise64 .deb found in internal_wiki)
2. Modify the vagrant to make and activate a `write_once` bucket type on provisioning
2. Fire up a VM
3. Using `pry` or `irb`, make some objects in that bucket type.
4. Observe behavior.

I still need to figure out what I expect to see though.

**Comment by Basho-JIRA** [comment]
As far as I can tell, this just kinda works. 

***[posted via JIRA by Bryce Kerley]***
