### ISSUE TITLE
Riak search instructions do not work [JIRA: CLIENTS-404]

### ISSUE THREAD

**Issue by mjbrender** [basho/riak-ruby-client#229]
It seems the section on search in this README is out of date. I'm not able to run recommended commands like `bucket_type = client.bucket_type 'yokozuna'`. 

The walkthrough [from this doc](http://docs.basho.com/riak/2.0.2/dev/using/search/) was the best resource and works with 2.1.1. Please update as you see appropriate.

**Comment by bkerley** [comment]
The README instructions on https://github.com/basho/riak-ruby-client are for the current development branch, which will become 2.2.0. This branch includes API additions that are in the development README but not in client version 2.1.1.

I'd like for the development cycle to be shorter, and that's something I need to work on going forwards. I don't see a way to change which version the README points to without changing other policies and practices in the repo though.
