### ISSUE TITLE
Cannot connect to Riak via SSL

### ISSUE THREAD

**Issue by Willux** [basho/riak-ruby-client#237]
I'm not a crypto expert, so help would certainly be appreciated in this regard.

Anytime I try to connect via Ruby (and thus use Protocol Buffers): I enter

`c = Riak::Client.new(host: [redacted, but not localhost], authentication: { user: [redacted], password: [redacted] })`

which creates a client object no problem. I test the client by entering:

`c.buckets` 

and I get the error:
`OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed`, which happens to be in 'gems/riak-client-2.2.0/lib/riak/client/beefcake/socket.rb:163'

The CA-Bundle is installed on the client side and the commands work if I send them over HTTPS via cURL.

Any details of what I am missing and/or how this can be resolved would be appreciated.

**Comment by bkerley** [comment]
Don't feel too bad, I've found TLS issues with Ruby's OpenSSL bindings to be very difficult to troubleshoot, and I understand the stuff!

The first thing I'd attempt is adding a `ca_file` to your authentication configuration: http://basho.github.io/riak-ruby-client/config.html#toc-security . It's possible that OpenSSL may not be looking in the right place for the CA-bundle.

If that doesn't work, there's some extra information we can grab with Wireshark, but that's a whole new world of complication, and even harder to redact.

**Comment by Willux** [comment]
That's what I was thinking. And I tried to hack the OpenSSL Ruby API by overriding the CERT_DIR (please don't kill me) to no avail. I'll try to follow the instructions you provided. Thank you

**Comment by bkerley** [comment]
Haha! Is CERT_DIR an environment variable? I don't believe we do anything in particular with it. 

Please let me know if the instructions work: I'd like to reference the error more explicitly, or even wrap it in a friendlier error. 

Also let me know if they don't work, for obvious reasons :)

**Comment by Willux** [comment]
yes, SSL_CERT_DIR was an environment variable. Hacky, but it was a desperate attempt to narrow down the issue :)

Also, including a ca_file to point to ca-bundle (ca-certificates.crt file since I am on Ubuntu) did not work. Still getting the same error. Will continue looking into it. If you find something of interest, please let me know

**Comment by bkerley** [comment]
Can you extract the particular CA cert from the bundle?

**Comment by Willux** [comment]
So I actually solved the problem.

Apparently in Riak config a CA File of its own was setup. Keep in mind that my app was living on a separate cluster than Riak. So I just scp'ed that CA file that was used in the config and passed it in as `ca_file`.

Either way, problem solved! And I feel a tad silly :smile:

**Comment by bkerley** [comment]
Thanks for pointing out possible issues anyways!

Would some kind of diagnostic tool that could grab a server cert or some kind of cert data from Riak have been useful?

**Comment by Willux** [comment]
Well, a more detailed error message would've been useful worst case :)

But that tool might save quite a bit of time as well. Especially if one is not a crypto expert.

**Comment by Basho-JIRA** [comment]
Fixed, or closed via GitHub issues. 

***[posted via JIRA by Alexander Moore]***
