### ISSUE TITLE
Timestamp value parsing [JIRA: CLIENTS-822]

### ISSUE THREAD

**Issue by davidx** [basho/riak-ruby-client#264]
When inspecting the timestamp value of serialized ruby objects from riak TS, it appears they all come from 1970 . values like:  1970-01-15 14:07:14.699999999 -08:00
When inspecting the data with riak-shell, it appears to be correct though. 
I created a little repo to help reproduce the issue. 

https://github.com/davidx/tsdateissue

Please let me know if you have any questions.
Thanks!

**Comment by ksauzz** [comment]
Hi, 
Looks like timestamp value is converted to [second](https://github.com/davidx/tsdateissue/blob/master/Rakefile#L35) by `strftime('%s)`. Could you try to convert timestamp value as msec by `strftime('%Q')`?

**Comment by lukebakken** [comment]
@davidx - this is the line you need to change:

https://github.com/davidx/tsdateissue/blob/master/Rakefile#L35

`"%s"` is *seconds* since the epoch, and Riak TS expects milliseconds.

**Comment by Basho-JIRA** [comment]
Fixed, or closed via GitHub issues. 

***[posted via JIRA by Alexander Moore]***
