### ISSUE TITLE
Finding objects by integer keys fail badly [JIRA: CLIENTS-865]

### ISSUE THREAD

**Issue by SavithaK** [basho/riak-ruby-client#266]
When using riak-ruby-client to find an object by id, https://github.com/basho/riak-ruby-client/blob/master/lib/riak/client/beefcake/object_methods.rb#L104 assumes that the key is a string.

IMO, the client should be agnostic about the type of the key or assume that it can be string-ified.

If we use an integer id to access data, we fail with:
TypeError: can't dup Fixnum
	from /home/ubuntu/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/riak-client-2.3.2/lib/riak/client/beefcake/object_methods.rb:104:in `dup'
	from /home/ubuntu/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/riak-client-2.3.2/lib/riak/client/beefcake/object_methods.rb:104:in `maybe_encode'
	from /home/ubuntu/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/riak-client-2.3.2/lib/riak/client/beefcake_protobuffs_backend.rb:92:in `fetch_object'
	from /home/ubuntu/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/riak-client-2.3.2/lib/riak/client.rb:266:in `block in get_object'
	from /home/ubuntu/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/riak-client-2.3.2/lib/riak/client.rb:358:in `block in recover_from'
	from /home/ubuntu/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/innertube-1.0.2/lib/innertube.rb:127:in `take'
	from /home/ubuntu/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/riak-client-2.3.2/lib/riak/client.rb:356:in `recover_from'
	from /home/ubuntu/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/riak-client-2.3.2/lib/riak/client.rb:328:in `protobuffs'
	from /home/ubuntu/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/riak-client-2.3.2/lib/riak/client.rb:265:in `get_object'
	from /home/ubuntu/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/riak-client-2.3.2/lib/riak/bucket.rb:106:in `get'

**Comment by lukebakken** [comment]
Hi @SavithaK -

The ruby client has always expected keys to be `String` objects. The reason is that Riak accepts any binary data as a key, and `String` is the best "container" for such data.

If you would like to provide a PR to implement conversion of other types to `String`, with associated tests, we would gladly review it.

Thanks -
Luke

**Comment by Basho-JIRA** [comment]
Fixed, or closed via GitHub issues. 

***[posted via JIRA by Alexander Moore]***
