### ISSUE TITLE
TimeSeries Query returning timestamps with rounding error [JIRA: CLIENTS-889]

### ISSUE THREAD

**Issue by bobhall** [basho/riak-ruby-client#274]
I'm querying RiakTS like this:

```
query_obj = Riak::TimeSeries::Query.new(@client, query)
results = query_obj.issue!

```

When I print the output, I see weird rounding errors, like this:

2016-03-31T17:07:50.102999
2016-03-31T17:12:08.805999

... When I expect this:

2016-03-31T17:07:50.103
2016-03-31T17:12:08.806

**Comment by lukebakken** [comment]
Hello,

Please provide this information:

* Your table definition
* The data you have inserted
* Your query
* The version of Ruby you're using
* The version of Riak TS you're using
* The version of the `riak-client` gem you're using

Thank you

**Comment by bobhall** [comment]
Table definition:

`riak-shell(9)>describe test_bob;
+-------------+---------+-------+-----------+---------+
|   Column    |  Type   |Is Null|Primary Key|Local Key|
+-------------+---------+-------+-----------+---------+
|   bob_id    | sint64  | false |     1     |    1    |
|creation_time|timestamp| false |     2     |    2    |
+-------------+---------+-------+-----------+---------+
`

Data I inserted:

`riak-shell(7)>select * from test_bob where bob_id=11 and creation_time > 1459382400000 and creation_time < 1459468800000;
+------+-------------+
|bob_id|creation_time|
+------+-------------+
|  11  |1459443822778|
|  11  |1459444070103|
+------+-------------+
`

Query:

`select * from test_bob where bob_id=11 and creation_time > 1459382400000 and creation_time < 1459468800000`

Ruby version:
ruby 2.0.0p353 (2013-11-22 revision 43784) [x86_64-linux]

Riak TS Version:
1.3

riak-client version:
2.3.2

**Comment by lukebakken** [comment]
Great, thank you.

**Comment by lukebakken** [comment]
One last question, just so I'm using the same code, what `strftime` format are you using?

**Comment by bobhall** [comment]
"%Y-%m-%dT%H:%M:%S.%6NZ"

**Comment by lukebakken** [comment]
I'm glad I asked!

**Comment by lukebakken** [comment]
Looks like I'm going to have to make the code a bit more intelligent:

```ruby
irb(main):010:0> Time.at(1459444070103 / 1000.0).strftime("%Y-%m-%dT%H:%M:%S.%6NZ")
=> "2016-03-31T10:07:50.102999Z"
```

Basically, this is [what is done here](https://github.com/basho/riak-ruby-client/blob/master/lib/riak/client/beefcake/ts_cell_codec.rb#L58-L61)

**Comment by lukebakken** [comment]
@bobhall I did some more research in `irb`. Note that using `to_f` on the `Time` object returned by `Time.at` *does* return the correct float value, but that using the `nsec` and `usec` methods reveals the difference due to the use of a float to store the value internally.

I recently changed the Python client to *not* auto-convert timestamp values to `datetime` objects since using integer values preserves accuracy. I could add a similar feature to the Ruby client to use integers rather than converting to `Time` objects. What do you think?

```ruby
irb(main):019:0> time = Time.at(1459444070103.to_f / 1000)
=> 2016-03-31 10:07:50 -0700
irb(main):020:0> time.to_f
=> 1459444070.103
irb(main):021:0> time.nsec
=> 102999925
irb(main):022:0> time.usec
=> 102999
irb(main):024:0> time.strftime("%Y-%m-%dT%H:%M:%S.%6NZ")
=> "2016-03-31T10:07:50.102999Z"
```

**Comment by lukebakken** [comment]
@bobhall the following code should resolve your issue, I'll get it in the next release:

```ruby
irb(main):010:0> t = 1459444070103
=> 1459444070103
irb(main):011:0> secs = t / 1000
=> 1459444070
irb(main):012:0> millis = t % 1000
=> 103
irb(main):013:0> Time.at(secs, millis * 1000)
=> 2016-03-31 10:07:50 -0700
irb(main):014:0> time = Time.at(secs, millis * 1000)
=> 2016-03-31 10:07:50 -0700
irb(main):015:0> time.strftime("%Y-%m-%dT%H:%M:%S.%6NZ")
=> "2016-03-31T10:07:50.103000Z"
```

I am still interested to know if you would find it useful to have *optional* conversion from Riak TS timestamp to `Time` objects.

**Comment by bobhall** [comment]
@lukebakken , thanks for the workaround.

It would be great to have an option to have RiakTS timestamps convert to Time objects or integers. It might be cool to have that be an option on the init method of the client itself (so you don't have to pass convert_to_time=true over and over, for example). The same option would be cool to have in the Python client as well.

**Comment by lukebakken** [comment]
Yep, that's how the [Python client works](https://github.com/basho/riak-python-client/blob/master/RELNOTES.md#252-release).

I'll implement something similar in Ruby, and, to be consistent, will make the default to be *no auto conversion*. That is the default in the Python client since it is used as middleware between Riak TS and other data consumers, so the conversion added a performance cost.

**Comment by bobhall** [comment]
Ah, so it does!
