### ISSUE TITLE
wait_for_finish should not be public [JIRA: CLIENTS-1054]

### ISSUE THREAD

**Issue by grosser** [basho/riak-ruby-client#301]
@lukebakken 

seems useless to me ... why would I wait when I don't want the results ...
so might as well call `results`

**Comment by lukebakken** [comment]
Can you add some context to this? Link to line numbers?

**Comment by grosser** [comment]
https://github.com/basho/riak-ruby-client/blob/master/lib/riak/multiget.rb#L87-L91

**Comment by lukebakken** [comment]
Thanks. No harm in having it public since it's such a simple method, plus someone may be using it.

**Comment by Basho-JIRA** [comment]
Fixed, or closed via GitHub issues. 

***[posted via JIRA by Alexander Moore]***
