### ISSUE TITLE
Add a socket timeout option to handle lingering socket requests on transitioning or mixed state nodes [JIRA: CLIENTS-624]

### ISSUE THREAD

**Issue by mk1s** [basho/riak-ruby-client#91]
There have been several recent problems with nodes  in various states transition whether it be physical or service(Riak) being up where the riak-ruby-client will try and connect for upwards of 60s or more, until if fails and tries the next node in the node list.  Some sites have been able to fix this by tweaking DNS. Suggested recommendation was to add an option to define a socket level timeout to provide more predictable behavior.

**Comment by sbimikesmullin** [comment]
+1 to get this merged upstream

**Comment by boosty** [comment]
I created a PR for setting custom socket timeouts: https://github.com/basho/riak-ruby-client/pull/265

**Comment by lukebakken** [comment]
Will be resolved by #270
